module.exports = {
  "vacancies": [{
    "id": 12610652,
    "sources": [{"sourceName": "hh.ru", "jobLink": "/Static/JobExternalJump/?jobId=12610652&sourceId=1"}],
    "isFavorite": false,
    "title": "Ведущий инженер ПТО",
    "updateDate": "2018-07-27T00:52:17.06",
    "region": {
      "id": 107,
      "name": "Москва и Московская область",
      "nameEn": null,
      "searchForm": null,
      "type": 0,
      "hasMetro": false,
      "subRegions": []
    },
    "city": {
      "id": 1029,
      "name": "Москва",
      "nameEn": null,
      "searchForm": null,
      "type": 0,
      "hasMetro": false,
      "subRegions": []
    },
    "metro": [],
    "monthIncomeFrom": 60000,
    "monthIncomeTo": 100000,
    "monthIncomeFromCurrency": 60000.0,
    "monthIncomeToCurrency": 100000.0,
    "employer": {
      "employeeId": 0,
      "id": 106748,
      "orgId": null,
      "name": "СиС",
      "simpleName": null,
      "displayName": "СиС",
      "exists": true
    },
    "crippleAllow": false,
    "occupation": ["Полная занятость"],
    "timeTable": ["Полный день"],
    "experience": "От 1 до 3 лет",
    "currencyRead": {
      "curs": 1.0,
      "name": "₽",
      "charCode": "RUB",
      "description": "Российский рубль",
      "currency": 0,
      "inUse": true
    },
    "publishDate": "2018-07-26T22:53:43",
    "responseDate": null,
    "searchRank": 0,
    "responseId": 0,
    "monthIncomeSort": 60000.0,
    "isArchive": false
  }, {
    "id": 11955877,
    "sources": [{"sourceName": "hh.ru", "jobLink": "/Static/JobExternalJump/?jobId=11955877&sourceId=1"}],
    "isFavorite": false,
    "title": "Старший Гейм-дизайнер (социальный покер)",
    "updateDate": "2018-07-27T00:32:29.523",
    "region": {
      "id": 107,
      "name": "Москва и Московская область",
      "nameEn": null,
      "searchForm": null,
      "type": 0,
      "hasMetro": false,
      "subRegions": []
    },
    "city": {
      "id": 1029,
      "name": "Москва",
      "nameEn": null,
      "searchForm": null,
      "type": 0,
      "hasMetro": false,
      "subRegions": []
    },
    "metro": [],
    "monthIncomeFrom": null,
    "monthIncomeTo": null,
    "monthIncomeFromCurrency": null,
    "monthIncomeToCurrency": null,
    "employer": {
      "employeeId": 0,
      "id": 106448,
      "orgId": null,
      "name": "Crazy Panda",
      "simpleName": null,
      "displayName": "Crazy Panda",
      "exists": true
    },
    "crippleAllow": false,
    "occupation": ["Полная занятость"],
    "timeTable": ["Полный день"],
    "experience": "От 3 до 6 лет",
    "currencyRead": {
      "curs": 1.0,
      "name": "₽",
      "charCode": "RUB",
      "description": "Российский рубль",
      "currency": 0,
      "inUse": true
    },
    "publishDate": "2018-07-26T21:59:55",
    "responseDate": null,
    "searchRank": 0,
    "responseId": 0,
    "monthIncomeSort": null,
    "isArchive": false
  }, {
    "id": 12085761,
    "sources": [{"sourceName": "hh.ru", "jobLink": "/Static/JobExternalJump/?jobId=12085761&sourceId=1"}],
    "isFavorite": false,
    "title": "Internet Marketing Manager (remote)",
    "updateDate": "2018-07-27T00:32:54.71",
    "region": {
      "id": 107,
      "name": "Москва и Московская область",
      "nameEn": null,
      "searchForm": null,
      "type": 0,
      "hasMetro": false,
      "subRegions": []
    },
    "city": {
      "id": 1029,
      "name": "Москва",
      "nameEn": null,
      "searchForm": null,
      "type": 0,
      "hasMetro": false,
      "subRegions": []
    },
    "metro": [],
    "monthIncomeFrom": 60000,
    "monthIncomeTo": 100000,
    "monthIncomeFromCurrency": 60000.0,
    "monthIncomeToCurrency": 100000.0,
    "employer": {
      "employeeId": 0,
      "id": 521507,
      "orgId": null,
      "name": "Soshace",
      "simpleName": null,
      "displayName": "Soshace",
      "exists": true
    },
    "crippleAllow": false,
    "occupation": ["Полная занятость"],
    "timeTable": ["Удаленная работа"],
    "experience": "От 3 до 6 лет",
    "currencyRead": {
      "curs": 1.0,
      "name": "₽",
      "charCode": "RUB",
      "description": "Российский рубль",
      "currency": 0,
      "inUse": true
    },
    "publishDate": "2018-07-26T21:59:28",
    "responseDate": null,
    "searchRank": 0,
    "responseId": 0,
    "monthIncomeSort": 60000.0,
    "isArchive": false
  }, {
    "id": 12759985,
    "sources": [{"sourceName": "hh.ru", "jobLink": "/Static/JobExternalJump/?jobId=12759985&sourceId=1"}],
    "isFavorite": false,
    "title": "Маркетолог",
    "updateDate": "2018-07-26T21:31:55",
    "region": {
      "id": 107,
      "name": "Москва и Московская область",
      "nameEn": null,
      "searchForm": null,
      "type": 0,
      "hasMetro": false,
      "subRegions": []
    },
    "city": {
      "id": 1029,
      "name": "Москва",
      "nameEn": null,
      "searchForm": null,
      "type": 0,
      "hasMetro": false,
      "subRegions": []
    },
    "metro": [],
    "monthIncomeFrom": 15000,
    "monthIncomeTo": 150000,
    "monthIncomeFromCurrency": 15000.0,
    "monthIncomeToCurrency": 150000.0,
    "employer": {
      "employeeId": 0,
      "id": 13168401,
      "orgId": null,
      "name": "РЕГ-Ц",
      "simpleName": null,
      "displayName": "РЕГ-Ц",
      "exists": true
    },
    "crippleAllow": false,
    "occupation": ["Частичная занятость"],
    "timeTable": ["Гибкий график"],
    "experience": "От 1 до 3 лет",
    "currencyRead": {
      "curs": 1.0,
      "name": "₽",
      "charCode": "RUB",
      "description": "Российский рубль",
      "currency": 0,
      "inUse": true
    },
    "publishDate": "2018-07-26T21:31:55",
    "responseDate": null,
    "searchRank": 0,
    "responseId": 0,
    "monthIncomeSort": 15000.0,
    "isArchive": false
  }, {
    "id": 12353145,
    "sources": [{"sourceName": "hh.ru", "jobLink": "/Static/JobExternalJump/?jobId=12353145&sourceId=1"}],
    "isFavorite": false,
    "title": "Комьюнити-менеджер со знанием английского языка/Community manager",
    "updateDate": "2018-07-27T00:45:33.54",
    "region": {
      "id": 107,
      "name": "Москва и Московская область",
      "nameEn": null,
      "searchForm": null,
      "type": 0,
      "hasMetro": false,
      "subRegions": []
    },
    "city": {
      "id": 1029,
      "name": "Москва",
      "nameEn": null,
      "searchForm": null,
      "type": 0,
      "hasMetro": false,
      "subRegions": []
    },
    "metro": [],
    "monthIncomeFrom": null,
    "monthIncomeTo": null,
    "monthIncomeFromCurrency": null,
    "monthIncomeToCurrency": null,
    "employer": {
      "employeeId": 0,
      "id": 701765,
      "orgId": null,
      "name": "AdMe",
      "simpleName": null,
      "displayName": "AdMe",
      "exists": true
    },
    "crippleAllow": false,
    "occupation": ["Полная занятость"],
    "timeTable": ["Гибкий график"],
    "experience": "От 1 до 3 лет",
    "currencyRead": {
      "curs": 1.0,
      "name": "₽",
      "charCode": "RUB",
      "description": "Российский рубль",
      "currency": 0,
      "inUse": true
    },
    "publishDate": "2018-07-26T21:30:30",
    "responseDate": null,
    "searchRank": 0,
    "responseId": 0,
    "monthIncomeSort": null,
    "isArchive": false
  }, {
    "id": 12760033,
    "sources": [{"sourceName": "hh.ru", "jobLink": "/Static/JobExternalJump/?jobId=12760033&sourceId=1"}],
    "isFavorite": false,
    "title": "Работник склада",
    "updateDate": "2018-07-26T21:26:25",
    "region": {
      "id": 107,
      "name": "Москва и Московская область",
      "nameEn": null,
      "searchForm": null,
      "type": 0,
      "hasMetro": false,
      "subRegions": []
    },
    "city": {
      "id": 1029,
      "name": "Москва",
      "nameEn": null,
      "searchForm": null,
      "type": 0,
      "hasMetro": false,
      "subRegions": []
    },
    "metro": [],
    "monthIncomeFrom": 33000,
    "monthIncomeTo": 42000,
    "monthIncomeFromCurrency": 33000.0,
    "monthIncomeToCurrency": 42000.0,
    "employer": {
      "employeeId": 0,
      "id": 13188522,
      "orgId": null,
      "name": "Актив",
      "simpleName": null,
      "displayName": "Актив",
      "exists": true
    },
    "crippleAllow": false,
    "occupation": ["Полная занятость"],
    "timeTable": ["Полный день"],
    "experience": "Нет опыта",
    "currencyRead": {
      "curs": 1.0,
      "name": "₽",
      "charCode": "RUB",
      "description": "Российский рубль",
      "currency": 0,
      "inUse": true
    },
    "publishDate": "2018-07-26T21:26:25",
    "responseDate": null,
    "searchRank": 0,
    "responseId": 0,
    "monthIncomeSort": 33000.0,
    "isArchive": false
  }, {
    "id": 12530983,
    "sources": [{"sourceName": "hh.ru", "jobLink": "/Static/JobExternalJump/?jobId=12530983&sourceId=1"}],
    "isFavorite": false,
    "title": "Ведущий специалист по работе с Клиентами (Госзакупки 44-ФЗ, 223-ФЗ)",
    "updateDate": "2018-07-26T22:14:33.41",
    "region": {
      "id": 107,
      "name": "Москва и Московская область",
      "nameEn": null,
      "searchForm": null,
      "type": 0,
      "hasMetro": false,
      "subRegions": []
    },
    "city": {
      "id": 1029,
      "name": "Москва",
      "nameEn": null,
      "searchForm": null,
      "type": 0,
      "hasMetro": false,
      "subRegions": []
    },
    "metro": [{"id": 120, "name": "Полежаевская", "color": "#8A2BE2"}],
    "monthIncomeFrom": null,
    "monthIncomeTo": null,
    "monthIncomeFromCurrency": null,
    "monthIncomeToCurrency": null,
    "employer": {
      "employeeId": 0,
      "id": 13353715,
      "orgId": null,
      "name": "Тендерное бюро В.А.Кожухова (ИП Кожухов В.А.)",
      "simpleName": null,
      "displayName": "Тендерное бюро В.А.Кожухова (ИП Кожухов В.А.)",
      "exists": true
    },
    "crippleAllow": false,
    "occupation": ["Полная занятость"],
    "timeTable": ["Полный день"],
    "experience": "От 3 до 6 лет",
    "currencyRead": {
      "curs": 1.0,
      "name": "₽",
      "charCode": "RUB",
      "description": "Российский рубль",
      "currency": 0,
      "inUse": true
    },
    "publishDate": "2018-07-26T21:22:58",
    "responseDate": null,
    "searchRank": 0,
    "responseId": 0,
    "monthIncomeSort": null,
    "isArchive": false
  }, {
    "id": 12759499,
    "sources": [{"sourceName": "hh.ru", "jobLink": "/Static/JobExternalJump/?jobId=12759499&sourceId=1"}],
    "isFavorite": false,
    "title": "Руководитель call-центра",
    "updateDate": "2018-07-26T21:21:29",
    "region": {
      "id": 107,
      "name": "Москва и Московская область",
      "nameEn": null,
      "searchForm": null,
      "type": 0,
      "hasMetro": false,
      "subRegions": []
    },
    "city": {
      "id": 1029,
      "name": "Москва",
      "nameEn": null,
      "searchForm": null,
      "type": 0,
      "hasMetro": false,
      "subRegions": []
    },
    "metro": [{"id": 106, "name": "Профсоюзная", "color": "#FFA500"}],
    "monthIncomeFrom": 60000,
    "monthIncomeTo": 80000,
    "monthIncomeFromCurrency": 60000.0,
    "monthIncomeToCurrency": 80000.0,
    "employer": {
      "employeeId": 0,
      "id": 13342189,
      "orgId": null,
      "name": "РОО Ассоциация победителей олимпиад",
      "simpleName": null,
      "displayName": "РОО Ассоциация победителей олимпиад",
      "exists": true
    },
    "crippleAllow": false,
    "occupation": ["Полная занятость"],
    "timeTable": ["Полный день"],
    "experience": "От 1 до 3 лет",
    "currencyRead": {
      "curs": 1.0,
      "name": "₽",
      "charCode": "RUB",
      "description": "Российский рубль",
      "currency": 0,
      "inUse": true
    },
    "publishDate": "2018-07-26T21:21:29",
    "responseDate": null,
    "searchRank": 0,
    "responseId": 0,
    "monthIncomeSort": 60000.0,
    "isArchive": false
  }, {
    "id": 12759310,
    "sources": [{"sourceName": "hh.ru", "jobLink": "/Static/JobExternalJump/?jobId=12759310&sourceId=1"}],
    "isFavorite": false,
    "title": "Продавец-флорист",
    "updateDate": "2018-07-26T21:21:21",
    "region": {
      "id": 107,
      "name": "Москва и Московская область",
      "nameEn": null,
      "searchForm": null,
      "type": 0,
      "hasMetro": false,
      "subRegions": []
    },
    "city": {
      "id": 1029,
      "name": "Москва",
      "nameEn": null,
      "searchForm": null,
      "type": 0,
      "hasMetro": false,
      "subRegions": []
    },
    "metro": [],
    "monthIncomeFrom": 60000,
    "monthIncomeTo": 70000,
    "monthIncomeFromCurrency": 60000.0,
    "monthIncomeToCurrency": 70000.0,
    "employer": {
      "employeeId": 0,
      "id": 13341941,
      "orgId": null,
      "name": "Сорокин Юрий Павлович",
      "simpleName": null,
      "displayName": "Сорокин Юрий Павлович",
      "exists": true
    },
    "crippleAllow": false,
    "occupation": ["Полная занятость"],
    "timeTable": ["Полный день"],
    "experience": "От 3 до 6 лет",
    "currencyRead": {
      "curs": 1.0,
      "name": "₽",
      "charCode": "RUB",
      "description": "Российский рубль",
      "currency": 0,
      "inUse": true
    },
    "publishDate": "2018-07-26T21:21:21",
    "responseDate": null,
    "searchRank": 0,
    "responseId": 0,
    "monthIncomeSort": 60000.0,
    "isArchive": false
  }, {
    "id": 12760237,
    "sources": [{"sourceName": "hh.ru", "jobLink": "/Static/JobExternalJump/?jobId=12760237&sourceId=1"}],
    "isFavorite": false,
    "title": "Scriptwriter for Bright Side",
    "updateDate": "2018-07-26T21:20:54",
    "region": {
      "id": 107,
      "name": "Москва и Московская область",
      "nameEn": null,
      "searchForm": null,
      "type": 0,
      "hasMetro": false,
      "subRegions": []
    },
    "city": {
      "id": 1029,
      "name": "Москва",
      "nameEn": null,
      "searchForm": null,
      "type": 0,
      "hasMetro": false,
      "subRegions": []
    },
    "metro": [],
    "monthIncomeFrom": null,
    "monthIncomeTo": null,
    "monthIncomeFromCurrency": null,
    "monthIncomeToCurrency": null,
    "employer": {
      "employeeId": 0,
      "id": 701765,
      "orgId": null,
      "name": "AdMe",
      "simpleName": null,
      "displayName": "AdMe",
      "exists": true
    },
    "crippleAllow": false,
    "occupation": ["Частичная занятость"],
    "timeTable": ["Удаленная работа"],
    "experience": "От 1 до 3 лет",
    "currencyRead": {
      "curs": 1.0,
      "name": "₽",
      "charCode": "RUB",
      "description": "Российский рубль",
      "currency": 0,
      "inUse": true
    },
    "publishDate": "2018-07-26T21:20:54",
    "responseDate": null,
    "searchRank": 0,
    "responseId": 0,
    "monthIncomeSort": null,
    "isArchive": false
  }, {
    "id": 12759894,
    "sources": [{"sourceName": "hh.ru", "jobLink": "/Static/JobExternalJump/?jobId=12759894&sourceId=1"}],
    "isFavorite": false,
    "title": "Главный инженер",
    "updateDate": "2018-07-26T21:19:08",
    "region": {
      "id": 107,
      "name": "Москва и Московская область",
      "nameEn": null,
      "searchForm": null,
      "type": 0,
      "hasMetro": false,
      "subRegions": []
    },
    "city": {
      "id": 1029,
      "name": "Москва",
      "nameEn": null,
      "searchForm": null,
      "type": 0,
      "hasMetro": false,
      "subRegions": []
    },
    "metro": [{"id": 80, "name": "Добрынинская", "color": "#8B5A00"}],
    "monthIncomeFrom": 60000,
    "monthIncomeTo": 60000,
    "monthIncomeFromCurrency": 60000.0,
    "monthIncomeToCurrency": 60000.0,
    "employer": {
      "employeeId": 0,
      "id": 169275,
      "orgId": null,
      "name": "Евро Строй Груп",
      "simpleName": null,
      "displayName": "Евро Строй Груп",
      "exists": true
    },
    "crippleAllow": false,
    "occupation": ["Полная занятость"],
    "timeTable": ["Полный день"],
    "experience": "Более 6 лет",
    "currencyRead": {
      "curs": 1.0,
      "name": "₽",
      "charCode": "RUB",
      "description": "Российский рубль",
      "currency": 0,
      "inUse": true
    },
    "publishDate": "2018-07-26T21:19:08",
    "responseDate": null,
    "searchRank": 0,
    "responseId": 0,
    "monthIncomeSort": 60000.0,
    "isArchive": false
  }, {
    "id": 12758409,
    "sources": [{"sourceName": "hh.ru", "jobLink": "/Static/JobExternalJump/?jobId=12758409&sourceId=1"}],
    "isFavorite": false,
    "title": "Бухгалтер",
    "updateDate": "2018-07-26T21:10:29",
    "region": {
      "id": 107,
      "name": "Москва и Московская область",
      "nameEn": null,
      "searchForm": null,
      "type": 0,
      "hasMetro": false,
      "subRegions": []
    },
    "city": {
      "id": 1029,
      "name": "Москва",
      "nameEn": null,
      "searchForm": null,
      "type": 0,
      "hasMetro": false,
      "subRegions": []
    },
    "metro": [],
    "monthIncomeFrom": 60000,
    "monthIncomeTo": null,
    "monthIncomeFromCurrency": 60000.0,
    "monthIncomeToCurrency": null,
    "employer": {
      "employeeId": 0,
      "id": 20842,
      "orgId": null,
      "name": "Восток, Энергосбытовая компания",
      "simpleName": null,
      "displayName": "Восток, Энергосбытовая компания",
      "exists": true
    },
    "crippleAllow": false,
    "occupation": ["Полная занятость"],
    "timeTable": ["Полный день"],
    "experience": "От 3 до 6 лет",
    "currencyRead": {
      "curs": 1.0,
      "name": "₽",
      "charCode": "RUB",
      "description": "Российский рубль",
      "currency": 0,
      "inUse": true
    },
    "publishDate": "2018-07-26T21:10:29",
    "responseDate": null,
    "searchRank": 0,
    "responseId": 0,
    "monthIncomeSort": 60000.0,
    "isArchive": false
  }, {
    "id": 12759309,
    "sources": [{"sourceName": "hh.ru", "jobLink": "/Static/JobExternalJump/?jobId=12759309&sourceId=1"}],
    "isFavorite": false,
    "title": "Ночной флорист",
    "updateDate": "2018-07-26T21:03:13",
    "region": {
      "id": 107,
      "name": "Москва и Московская область",
      "nameEn": null,
      "searchForm": null,
      "type": 0,
      "hasMetro": false,
      "subRegions": []
    },
    "city": {
      "id": 1029,
      "name": "Москва",
      "nameEn": null,
      "searchForm": null,
      "type": 0,
      "hasMetro": false,
      "subRegions": []
    },
    "metro": [],
    "monthIncomeFrom": 50000,
    "monthIncomeTo": 60000,
    "monthIncomeFromCurrency": 50000.0,
    "monthIncomeToCurrency": 60000.0,
    "employer": {
      "employeeId": 0,
      "id": 13341941,
      "orgId": null,
      "name": "Сорокин Юрий Павлович",
      "simpleName": null,
      "displayName": "Сорокин Юрий Павлович",
      "exists": true
    },
    "crippleAllow": false,
    "occupation": ["Полная занятость"],
    "timeTable": ["Полный день"],
    "experience": "От 1 до 3 лет",
    "currencyRead": {
      "curs": 1.0,
      "name": "₽",
      "charCode": "RUB",
      "description": "Российский рубль",
      "currency": 0,
      "inUse": true
    },
    "publishDate": "2018-07-26T21:03:13",
    "responseDate": null,
    "searchRank": 0,
    "responseId": 0,
    "monthIncomeSort": 50000.0,
    "isArchive": false
  }, {
    "id": 12658071,
    "sources": [{"sourceName": "hh.ru", "jobLink": "/Static/JobExternalJump/?jobId=12658071&sourceId=1"}],
    "isFavorite": false,
    "title": "Ретушер",
    "updateDate": "2018-07-26T21:02:15.663",
    "region": {
      "id": 107,
      "name": "Москва и Московская область",
      "nameEn": null,
      "searchForm": null,
      "type": 0,
      "hasMetro": false,
      "subRegions": []
    },
    "city": {
      "id": 1029,
      "name": "Москва",
      "nameEn": null,
      "searchForm": null,
      "type": 0,
      "hasMetro": false,
      "subRegions": []
    },
    "metro": [],
    "monthIncomeFrom": null,
    "monthIncomeTo": 45000,
    "monthIncomeFromCurrency": null,
    "monthIncomeToCurrency": 45000.0,
    "employer": {
      "employeeId": 0,
      "id": 17323,
      "orgId": null,
      "name": "Итал Базар",
      "simpleName": null,
      "displayName": "Итал Базар",
      "exists": true
    },
    "crippleAllow": false,
    "occupation": ["Полная занятость"],
    "timeTable": ["Полный день"],
    "experience": "От 1 до 3 лет",
    "currencyRead": {
      "curs": 1.0,
      "name": "₽",
      "charCode": "RUB",
      "description": "Российский рубль",
      "currency": 0,
      "inUse": true
    },
    "publishDate": "2018-07-26T20:38:17",
    "responseDate": null,
    "searchRank": 0,
    "responseId": 0,
    "monthIncomeSort": 45000.0,
    "isArchive": false
  }, {
    "id": 12660280,
    "sources": [{"sourceName": "hh.ru", "jobLink": "/Static/JobExternalJump/?jobId=12660280&sourceId=1"}],
    "isFavorite": false,
    "title": "Инженер пуско-наладочных работ",
    "updateDate": "2018-07-26T21:47:08.313",
    "region": {
      "id": 107,
      "name": "Москва и Московская область",
      "nameEn": null,
      "searchForm": null,
      "type": 0,
      "hasMetro": false,
      "subRegions": []
    },
    "city": {
      "id": 1029,
      "name": "Москва",
      "nameEn": null,
      "searchForm": null,
      "type": 0,
      "hasMetro": false,
      "subRegions": []
    },
    "metro": [],
    "monthIncomeFrom": 45000,
    "monthIncomeTo": null,
    "monthIncomeFromCurrency": 45000.0,
    "monthIncomeToCurrency": null,
    "employer": {
      "employeeId": 0,
      "id": 13355324,
      "orgId": null,
      "name": "Многопрофильная Инженерная Компания",
      "simpleName": null,
      "displayName": "Многопрофильная Инженерная Компания",
      "exists": true
    },
    "crippleAllow": false,
    "occupation": ["Полная занятость"],
    "timeTable": ["Полный день"],
    "experience": "От 1 до 3 лет",
    "currencyRead": {
      "curs": 1.0,
      "name": "₽",
      "charCode": "RUB",
      "description": "Российский рубль",
      "currency": 0,
      "inUse": true
    },
    "publishDate": "2018-07-26T20:31:07",
    "responseDate": null,
    "searchRank": 0,
    "responseId": 0,
    "monthIncomeSort": 45000.0,
    "isArchive": false
  }, {
    "id": 12401170,
    "sources": [{"sourceName": "career.ru", "jobLink": "/Static/JobExternalJump/?jobId=12401170&sourceId=1"}],
    "isFavorite": false,
    "title": "Рекрутер",
    "updateDate": "2018-07-26T21:43:34.74",
    "region": {
      "id": 107,
      "name": "Москва и Московская область",
      "nameEn": null,
      "searchForm": null,
      "type": 0,
      "hasMetro": false,
      "subRegions": []
    },
    "city": {
      "id": 1029,
      "name": "Москва",
      "nameEn": null,
      "searchForm": null,
      "type": 0,
      "hasMetro": false,
      "subRegions": []
    },
    "metro": [],
    "monthIncomeFrom": 20000,
    "monthIncomeTo": null,
    "monthIncomeFromCurrency": 20000.0,
    "monthIncomeToCurrency": null,
    "employer": {
      "employeeId": 0,
      "id": 13339087,
      "orgId": null,
      "name": "KMA.BIZ",
      "simpleName": null,
      "displayName": "KMA.BIZ",
      "exists": true
    },
    "crippleAllow": false,
    "occupation": ["Полная занятость"],
    "timeTable": ["Удаленная работа"],
    "experience": "От 1 до 3 лет",
    "currencyRead": {
      "curs": 1.0,
      "name": "₽",
      "charCode": "RUB",
      "description": "Российский рубль",
      "currency": 0,
      "inUse": true
    },
    "publishDate": "2018-07-26T20:24:18",
    "responseDate": null,
    "searchRank": 0,
    "responseId": 0,
    "monthIncomeSort": 20000.0,
    "isArchive": false
  }, {
    "id": 12240047,
    "sources": [{"sourceName": "hh.ru", "jobLink": "/Static/JobExternalJump/?jobId=12240047&sourceId=1"}],
    "isFavorite": false,
    "title": "Креативный менеджер (creator)",
    "updateDate": "2018-07-26T21:12:06.66",
    "region": {
      "id": 107,
      "name": "Москва и Московская область",
      "nameEn": null,
      "searchForm": null,
      "type": 0,
      "hasMetro": false,
      "subRegions": []
    },
    "city": {
      "id": 1029,
      "name": "Москва",
      "nameEn": null,
      "searchForm": null,
      "type": 0,
      "hasMetro": false,
      "subRegions": []
    },
    "metro": [],
    "monthIncomeFrom": 50000,
    "monthIncomeTo": null,
    "monthIncomeFromCurrency": 50000.0,
    "monthIncomeToCurrency": null,
    "employer": {
      "employeeId": 0,
      "id": 20061,
      "orgId": null,
      "name": "Atomic",
      "simpleName": null,
      "displayName": "Atomic",
      "exists": true
    },
    "crippleAllow": false,
    "occupation": ["Полная занятость"],
    "timeTable": ["Полный день"],
    "experience": "От 1 до 3 лет",
    "currencyRead": {
      "curs": 1.0,
      "name": "₽",
      "charCode": "RUB",
      "description": "Российский рубль",
      "currency": 0,
      "inUse": true
    },
    "publishDate": "2018-07-26T20:18:03",
    "responseDate": null,
    "searchRank": 0,
    "responseId": 0,
    "monthIncomeSort": 50000.0,
    "isArchive": false
  }, {
    "id": 12374685,
    "sources": [{"sourceName": "hh.ru", "jobLink": "/Static/JobExternalJump/?jobId=12374685&sourceId=1"}],
    "isFavorite": false,
    "title": "Руководитель отдела продаж B2B",
    "updateDate": "2018-07-26T20:30:19.587",
    "region": {
      "id": 107,
      "name": "Москва и Московская область",
      "nameEn": null,
      "searchForm": null,
      "type": 0,
      "hasMetro": false,
      "subRegions": []
    },
    "city": {
      "id": 1029,
      "name": "Москва",
      "nameEn": null,
      "searchForm": null,
      "type": 0,
      "hasMetro": false,
      "subRegions": []
    },
    "metro": [],
    "monthIncomeFrom": 180000,
    "monthIncomeTo": null,
    "monthIncomeFromCurrency": 180000.0,
    "monthIncomeToCurrency": null,
    "employer": {
      "employeeId": 0,
      "id": 9632,
      "orgId": null,
      "name": "БТК групп",
      "simpleName": null,
      "displayName": "БТК групп",
      "exists": true
    },
    "crippleAllow": false,
    "occupation": ["Полная занятость"],
    "timeTable": ["Полный день"],
    "experience": "От 3 до 6 лет",
    "currencyRead": {
      "curs": 1.0,
      "name": "₽",
      "charCode": "RUB",
      "description": "Российский рубль",
      "currency": 0,
      "inUse": true
    },
    "publishDate": "2018-07-26T20:16:05",
    "responseDate": null,
    "searchRank": 0,
    "responseId": 0,
    "monthIncomeSort": 180000.0,
    "isArchive": false
  }, {
    "id": 12374664,
    "sources": [{"sourceName": "hh.ru", "jobLink": "/Static/JobExternalJump/?jobId=12374664&sourceId=1"}],
    "isFavorite": false,
    "title": "Ведущий менеджер по работе с корпоративными клиентами / КАМ",
    "updateDate": "2018-07-26T20:30:28.273",
    "region": {
      "id": 107,
      "name": "Москва и Московская область",
      "nameEn": null,
      "searchForm": null,
      "type": 0,
      "hasMetro": false,
      "subRegions": []
    },
    "city": {
      "id": 1029,
      "name": "Москва",
      "nameEn": null,
      "searchForm": null,
      "type": 0,
      "hasMetro": false,
      "subRegions": []
    },
    "metro": [],
    "monthIncomeFrom": null,
    "monthIncomeTo": null,
    "monthIncomeFromCurrency": null,
    "monthIncomeToCurrency": null,
    "employer": {
      "employeeId": 0,
      "id": 9632,
      "orgId": null,
      "name": "БТК групп",
      "simpleName": null,
      "displayName": "БТК групп",
      "exists": true
    },
    "crippleAllow": false,
    "occupation": ["Полная занятость"],
    "timeTable": ["Полный день"],
    "experience": "От 3 до 6 лет",
    "currencyRead": {
      "curs": 1.0,
      "name": "₽",
      "charCode": "RUB",
      "description": "Российский рубль",
      "currency": 0,
      "inUse": true
    },
    "publishDate": "2018-07-26T20:15:59",
    "responseDate": null,
    "searchRank": 0,
    "responseId": 0,
    "monthIncomeSort": null,
    "isArchive": false
  }, {
    "id": 12374666,
    "sources": [{"sourceName": "hh.ru", "jobLink": "/Static/JobExternalJump/?jobId=12374666&sourceId=1"}],
    "isFavorite": false,
    "title": "Специалист по информационной безопасности",
    "updateDate": "2018-07-26T20:28:49.737",
    "region": {
      "id": 107,
      "name": "Москва и Московская область",
      "nameEn": null,
      "searchForm": null,
      "type": 0,
      "hasMetro": false,
      "subRegions": []
    },
    "city": {
      "id": 1029,
      "name": "Москва",
      "nameEn": null,
      "searchForm": null,
      "type": 0,
      "hasMetro": false,
      "subRegions": []
    },
    "metro": [],
    "monthIncomeFrom": null,
    "monthIncomeTo": null,
    "monthIncomeFromCurrency": null,
    "monthIncomeToCurrency": null,
    "employer": {
      "employeeId": 0,
      "id": 9632,
      "orgId": null,
      "name": "БТК групп",
      "simpleName": null,
      "displayName": "БТК групп",
      "exists": true
    },
    "crippleAllow": false,
    "occupation": ["Полная занятость"],
    "timeTable": ["Полный день"],
    "experience": "От 3 до 6 лет",
    "currencyRead": {
      "curs": 1.0,
      "name": "₽",
      "charCode": "RUB",
      "description": "Российский рубль",
      "currency": 0,
      "inUse": true
    },
    "publishDate": "2018-07-26T20:15:53",
    "responseDate": null,
    "searchRank": 0,
    "responseId": 0,
    "monthIncomeSort": null,
    "isArchive": false
  }],
  "count": 253579
};